/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAttestationVerifier__factory } from "./IAttestationVerifier__factory";
export { IValidator__factory } from "./IValidator__factory";
