/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockAttestationVerifierSol from "./MockAttestationVerifier.sol";
export * as uniswapV2 from "./uniswapV2";
