/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MockAttesetationVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "setVerifierEnclaveKey"
      | "verifierEnclaveKey"
      | "verifyAttestationSig"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setVerifierEnclaveKey",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifierEnclaveKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttestationSig",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "setVerifierEnclaveKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifierEnclaveKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttestationSig",
    data: BytesLike
  ): Result;
}

export interface MockAttesetationVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): MockAttesetationVerifier;
  waitForDeployment(): Promise<this>;

  interface: MockAttesetationVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  setVerifierEnclaveKey: TypedContractMethod<
    [_verifierEnclaveKey: AddressLike],
    [void],
    "nonpayable"
  >;

  verifierEnclaveKey: TypedContractMethod<[], [string], "view">;

  verifyAttestationSig: TypedContractMethod<
    [_attestationSig: BytesLike, _enclaveKey: AddressLike, _imageId: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "setVerifierEnclaveKey"
  ): TypedContractMethod<
    [_verifierEnclaveKey: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifierEnclaveKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyAttestationSig"
  ): TypedContractMethod<
    [_attestationSig: BytesLike, _enclaveKey: AddressLike, _imageId: BytesLike],
    [string],
    "view"
  >;

  filters: {};
}
