/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockAttestationVerifierSol from "./MockAttestationVerifier.sol";
export type { mockAttestationVerifierSol };
import type * as uniswapV2 from "./uniswapV2";
export type { uniswapV2 };
